### PR TITLE
fix issue #3 and other enhancements

### PR DESCRIPTION
**Pull request by KristerV**
- fix issue #3 
- change delimiter possibility
- remove unconventional 'no data' string (leaving empty is standard)

### CODE REVIEW

**Comment by KristerV** [comment]
ok, good to merge. Done with updating.

edit: actually, adding heading row too!

**Comment by KristerV** [comment]
yep, done now.
nope, not yet... 

I'll merge when you think is ready

**Comment by KristerV** [comment]
lol did you edit my message? :D or is github acting strangely.

anyway i'm done now for sure. Export is working as I need.

**Comment by lfergon** [comment]
Yes, my fault. Merge is done. Thanks!!

**Comment by KristerV** [comment]
just reminding you to push the package to the meteor server as well (so I can `meteor update` and remove local package :))

**Comment by lfergon** [comment]
Published lfergon:exportcsv@0.0.8

**Comment by KristerV** [comment]
awesome!

**Pull request merged**
